In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
data = pd.read_csv("Social_Network_Ads.csv")

In [ ]:
data.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
data.describe()

              Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB

In [ ]:
data.Purchased.value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [ ]:
# Rules for Classification using ANN
# ==============================================
# 1. Data must be complete
# 2. Data must be strictly numeric
# 3. Features and label must be in the form of 2d np array
# 4. Scaling of features is OPTIONAL (But Prashant Nair apply the same rules of Scaling as in Regression)
# 5. For Label (MANDATORY)
#        a. Binary Classification: Label must be represented in the form of 0 or 1
#        b. Multiclass Classification: Label must be either DISCRETE NUMERICAL or DUMMY VARIABLE

In [ ]:
#Seperate data as features and label
features = data.iloc[:,[0,1]].values
label = data.iloc[:,[2]].values

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
features = sc.fit_transform(features)

In [ ]:
#Label Normalization
# Here data is by default 0 and 1 , so no changes/preprocessing required

In [ ]:
#Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(features,
                                                 label,
                                                 test_size=0.2,
                                                 random_state=10)

#ANN Modelling

# Changing Optimizer Algo

In [ ]:
#Architect the model
import tensorflow as tf

model = tf.keras.Sequential()

model.add(tf.keras.layers.Dense(units = 6 , activation="relu", input_shape=(2,)))
model.add(tf.keras.layers.Dense(units = 6 , activation="relu"))
model.add(tf.keras.layers.Dense(units = 1 , activation="sigmoid"))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
#Compile Model

#For Classification
# Loss Function:
# a. Binary Classification: binary_crossentropy
# b. Multi-class Classification: categorical_crossentropy | sparse_categorical_crossentropy


model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [ ]:
class MyCLRuleMonitor(tf.keras.callbacks.Callback):
  def __init__(self,cl):
    super(MyCLRuleMonitor,self).__init__()
    self.cl=cl

  def on_epoch_end(self,epoch,logs=None):
    testScore = logs['val_accuracy']
    trainScore = logs['accuracy']

    if testScore > trainScore and testScore >= self.cl:
      self.model.stop_training=True

In [ ]:
model.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=10000, callbacks=[MyCLRuleMonitor(0.9)])

Epoch 1/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 3s 91ms/step - accuracy: 0.3741 - loss: 0.6960 - val_accuracy: 0.3625 - val_loss: 0.6727
Epoch 2/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.3896 - loss: 0.6808 - val_accuracy: 0.4375 - val_loss: 0.6615
Epoch 3/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4889 - loss: 0.6731 - val_accuracy: 0.4875 - val_loss: 0.6511
Epoch 4/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5391 - loss: 0.6670 - val_accuracy: 0.5375 - val_loss: 0.6416
Epoch 5/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5698 - loss: 0.6513 - val_accuracy: 0.6000 - val_loss: 0.6331
Epoch 6/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6200 - loss: 0.6556 - val_accuracy: 0.6250 - val_loss: 0.6254
Epoch 7/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6296 - loss: 0.6405 - val_accuracy: 0.6750 - val_loss: 0.6183
Epoch 8/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6625 - loss: 0.6349 - val_accuracy: 0.6750 - val_loss: 0.6118
Epoch 9/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7175 - loss: 0.6320 - val_accuracy: 0.7125 - val_loss: 0.6056
Epoch 10/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7194 - loss: 0.6177 - val_accuracy: 0.7375 - val_loss: 0.5999
Epoch 11/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7043 - loss: 0.6217 - val_accuracy: 0.7375 - val_loss: 0.5943
Epoch 12/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7440 - loss: 0.6125 - val_accuracy: 0.7750 - val_loss: 0.5888
Epoch 13/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8028 - loss: 0.5819 - val_accuracy: 0.8250 - val_loss: 0.5834
Epoch 14/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7763 - loss: 0.6029 - val_accuracy: 0.8500 - val_loss: 0.5782
Epoch 15/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8295 - loss: 0.5960 - val_accuracy: 0.8625 - val_loss: 0.5730
Epoch 16/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8708 - loss: 0.5882 - val_accuracy: 0.8875 - val_loss: 0.5683
Epoch 17/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8882 - loss: 0.5761 - val_accuracy: 0.9000 - val_loss: 0.5634
Epoch 18/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8933 - loss: 0.5730 - val_accuracy: 0.9000 - val_loss: 0.5586
Epoch 19/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8614 - loss: 0.5824 - val_accuracy: 0.9000 - val_loss: 0.5539
Epoch 20/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8604 - loss: 0.5819 - val_accuracy: 0.9125 - val_loss: 0.5494

In [ ]:
#Try with nadam,rmsprop,adadelta,lion

# Tweak the Learning Rate Parameter

In [ ]:
#Architect the model
import tensorflow as tf

model1 = tf.keras.Sequential()

model1.add(tf.keras.layers.Dense(units = 6 , activation="relu", input_shape=(2,)))
model1.add(tf.keras.layers.Dense(units = 6 , activation="relu"))
model1.add(tf.keras.layers.Dense(units = 1 , activation="sigmoid"))

In [ ]:
#Compile Model

#For Classification
# Loss Function:
# a. Binary Classification: binary_crossentropy
# b. Multi-class Classification: categorical_crossentropy | sparse_categorical_crossentropy


model1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
               loss="binary_crossentropy",
               metrics=["accuracy"])

In [ ]:
class MyCLRuleMonitor(tf.keras.callbacks.Callback):
  def __init__(self,cl):
    super(MyCLRuleMonitor,self).__init__()
    self.cl=cl

  def on_epoch_end(self,epoch,logs=None):
    testScore = logs.get('val_accuracy')
    trainScore = logs.get('accuracy')

    if testScore > trainScore and testScore >= self.cl:
      self.model.stop_training=True

In [ ]:
model1.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=10000, callbacks=[MyCLRuleMonitor(0.9)])

Epoch 1/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step - accuracy: 0.6173 - loss: 0.6515 - val_accuracy: 0.8250 - val_loss: 0.5127
Epoch 2/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8373 - loss: 0.4651 - val_accuracy: 0.9000 - val_loss: 0.3876
Epoch 3/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8946 - loss: 0.3608 - val_accuracy: 0.9500 - val_loss: 0.3041

In [ ]:
#tf.keras.optimizers.Nadam(learning_rate=0.01)
#tf.keras.optimizers.RMSprop(learning_rate=0.01)
#tf.keras.optimizers.Adadelta(learning_rate=0.01)
#tf.keras.optimizers.Lion(learning_rate=0.01)

In [ ]:
#https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adadelta$0

# Tweak the momentum parameter

In [ ]:
#Architect the model
import tensorflow as tf

model2 = tf.keras.Sequential()

model2.add(tf.keras.layers.Dense(units = 6 , activation="relu", input_shape=(2,)))
model2.add(tf.keras.layers.Dense(units = 6 , activation="relu"))
model2.add(tf.keras.layers.Dense(units = 1 , activation="sigmoid"))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
#Compile Model

#For Classification
# Loss Function:
# a. Binary Classification: binary_crossentropy
# b. Multi-class Classification: categorical_crossentropy | sparse_categorical_crossentropy

#tf.keras.optimizers.SGD(momentum=0.2)
model2.compile(optimizer=tf.keras.optimizers.RMSprop(momentum=0.2), loss="binary_crossentropy", metrics=["accuracy"])

In [ ]:
class MyCLRuleMonitor(tf.keras.callbacks.Callback):
  def __init__(self,cl):
    super(MyCLRuleMonitor,self).__init__()
    self.cl=cl

  def on_epoch_end(self,epoch,logs=None):
    testScore = logs['val_accuracy']
    trainScore = logs['accuracy']

    if testScore > trainScore and testScore >= self.cl:
      self.model.stop_training=True

In [ ]:
model2.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=10000, callbacks=[MyCLRuleMonitor(0.9)])

Epoch 1/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.5752 - loss: 0.6714 - val_accuracy: 0.8250 - val_loss: 0.6246
Epoch 2/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7431 - loss: 0.6455 - val_accuracy: 0.8500 - val_loss: 0.6027
Epoch 3/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7835 - loss: 0.6136 - val_accuracy: 0.8500 - val_loss: 0.5852
Epoch 4/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7707 - loss: 0.6072 - val_accuracy: 0.8750 - val_loss: 0.5690
Epoch 5/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8203 - loss: 0.5833 - val_accuracy: 0.8875 - val_loss: 0.5534
Epoch 6/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8264 - loss: 0.5680 - val_accuracy: 0.8875 - val_loss: 0.5384
Epoch 7/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8051 - loss: 0.5506 - val_accuracy: 0.9000 - val_loss: 0.5239
Epoch 8/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8012 - loss: 0.5468 - val_accuracy: 0.8875 - val_loss: 0.5101
Epoch 9/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8023 - loss: 0.5264 - val_accuracy: 0.8875 - val_loss: 0.4976
Epoch 10/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7996 - loss: 0.5232 - val_accuracy: 0.8875 - val_loss: 0.4861
Epoch 11/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8202 - loss: 0.5114 - val_accuracy: 0.8875 - val_loss: 0.4749
Epoch 12/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.5097 - val_accuracy: 0.8875 - val_loss: 0.4634
Epoch 13/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7960 - loss: 0.4993 - val_accuracy: 0.8875 - val_loss: 0.4518
Epoch 14/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8189 - loss: 0.4726 - val_accuracy: 0.8875 - val_loss: 0.4408
Epoch 15/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8040 - loss: 0.4694 - val_accuracy: 0.8875 - val_loss: 0.4295
Epoch 16/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8290 - loss: 0.4366 - val_accuracy: 0.8875 - val_loss: 0.4193
Epoch 17/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8140 - loss: 0.4539 - val_accuracy: 0.8875 - val_loss: 0.4098
Epoch 18/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8258 - loss: 0.4371 - val_accuracy: 0.8875 - val_loss: 0.4001
Epoch 19/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8496 - loss: 0.4162 - val_accuracy: 0.8875 - val_loss: 0.3908
Epoch 20/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8408 - loss: 0.4123 - val_accuracy: 0.8875 - val_loss: 0.3825
Epoch 21/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7939 - loss: 0.4140 - val_accuracy: 0.8875 - val_loss: 0.3738
Epoch 22/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8291 - loss: 0.3957 - val_accuracy: 0.8875 - val_loss: 0.3657
Epoch 23/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8408 - loss: 0.3994 - val_accuracy: 0.8875 - val_loss: 0.3576
Epoch 24/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8292 - loss: 0.3998 - val_accuracy: 0.8875 - val_loss: 0.3496
Epoch 25/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8457 - loss: 0.3844 - val_accuracy: 0.8875 - val_loss: 0.3422
Epoch 26/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8497 - loss: 0.3614 - val_accuracy: 0.8875 - val_loss: 0.3350
Epoch 27/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8383 - loss: 0.3728 - val_accuracy: 0.9000 - val_loss: 0.3283
Epoch 28/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8528 - loss: 0.3603 - val_accuracy: 0.9000 - val_loss: 0.3219
Epoch 29/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8609 - loss: 0.3618 - val_accuracy: 0.9000 - val_loss: 0.3166
Epoch 30/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8524 - loss: 0.3387 - val_accuracy: 0.9000 - val_loss: 0.3113
Epoch 31/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8629 - loss: 0.3523 - val_accuracy: 0.9125 - val_loss: 0.3058

# Dropout -- Regularization Strategy

In [ ]:
#Architect the model
import tensorflow as tf

model3 = tf.keras.Sequential()

model3.add(tf.keras.layers.Dense(units = 60 , activation="relu", input_shape=(2,))) #Input + h1
model3.add(tf.keras.layers.Dropout(0.5)) #Dropout applied in H2
model3.add(tf.keras.layers.Dense(units = 60 , activation="relu")) #h2
model3.add(tf.keras.layers.Dropout(0.8)) #Dropout applied on H3
model3.add(tf.keras.layers.Dense(units = 60 , activation="relu")) #h3
model3.add(tf.keras.layers.Dropout(0.8)) #Dropout applied on H4
model3.add(tf.keras.layers.Dense(units = 60 , activation="relu")) # h4
model3.add(tf.keras.layers.Dense(units = 1 , activation="sigmoid")) # output layer

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
#Compile Model

#For Classification
# Loss Function:
# a. Binary Classification: binary_crossentropy
# b. Multi-class Classification: categorical_crossentropy | sparse_categorical_crossentropy


model3.compile(optimizer=tf.keras.optimizers.RMSprop(momentum=0.2), loss="binary_crossentropy", metrics=["accuracy"])

In [ ]:
class MyCLRuleMonitor(tf.keras.callbacks.Callback):
  def __init__(self,cl):
    super(MyCLRuleMonitor,self).__init__()
    self.cl=cl

  def on_epoch_end(self,epoch,logs=None):
    testScore = logs['val_accuracy']
    trainScore = logs['accuracy']

    if testScore > trainScore and testScore >= self.cl:
      self.model.stop_training=True

In [ ]:
model3.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=10000, callbacks=[MyCLRuleMonitor(0.9)])

Epoch 1/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 4s 97ms/step - accuracy: 0.5777 - loss: 0.6938 - val_accuracy: 0.6500 - val_loss: 0.6613
Epoch 2/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6105 - loss: 0.6725 - val_accuracy: 0.6500 - val_loss: 0.6452
Epoch 3/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6864 - loss: 0.6556 - val_accuracy: 0.6500 - val_loss: 0.6232
Epoch 4/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6777 - loss: 0.6453 - val_accuracy: 0.6500 - val_loss: 0.6044
Epoch 5/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6249 - loss: 0.6782 - val_accuracy: 0.6500 - val_loss: 0.5864
Epoch 6/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6727 - loss: 0.6213 - val_accuracy: 0.6875 - val_loss: 0.5656
Epoch 7/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6431 - loss: 0.6207 - val_accuracy: 0.7000 - val_loss: 0.5369
Epoch 8/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6352 - loss: 0.6237 - val_accuracy: 0.7125 - val_loss: 0.5226
Epoch 9/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6903 - loss: 0.5959 - val_accuracy: 0.7125 - val_loss: 0.4957
Epoch 10/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7147 - loss: 0.5618 - val_accuracy: 0.7500 - val_loss: 0.4720
Epoch 11/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7305 - loss: 0.5733 - val_accuracy: 0.8125 - val_loss: 0.4434
Epoch 12/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7320 - loss: 0.5238 - val_accuracy: 0.8625 - val_loss: 0.4104
Epoch 13/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7203 - loss: 0.5430 - val_accuracy: 0.8750 - val_loss: 0.3904
Epoch 14/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7434 - loss: 0.5005 - val_accuracy: 0.8750 - val_loss: 0.3723
Epoch 15/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7814 - loss: 0.5519 - val_accuracy: 0.8750 - val_loss: 0.3575
Epoch 16/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7412 - loss: 0.4874 - val_accuracy: 0.8875 - val_loss: 0.3404
Epoch 17/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7418 - loss: 0.4882 - val_accuracy: 0.9000 - val_loss: 0.3260
Epoch 18/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7722 - loss: 0.5081 - val_accuracy: 0.9000 - val_loss: 0.3175
Epoch 19/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7606 - loss: 0.4516 - val_accuracy: 0.9000 - val_loss: 0.3025
Epoch 20/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7722 - loss: 0.4716 - val_accuracy: 0.9000 - val_loss: 0.2929
Epoch 21/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8047 - loss: 0.4432 - val_accuracy: 0.9125 - val_loss: 0.2789

# L1 Regularization

In [ ]:
#Architect the model
import tensorflow as tf

model4 = tf.keras.Sequential()

#kernel regularizer --- Penalty in deltaW
#bias regularizer ----- Penalty is applied on deltaB

model4.add(tf.keras.layers.Dense(units = 6 , kernel_regularizer='l1', activation="relu", input_shape=(2,)))
model4.add(tf.keras.layers.Dense(units = 6 , kernel_regularizer='l1' , activation="relu"))
model4.add(tf.keras.layers.Dense(units = 1 , activation="sigmoid"))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
#Compile Model

#For Classification
# Loss Function:
# a. Binary Classification: binary_crossentropy
# b. Multi-class Classification: categorical_crossentropy | sparse_categorical_crossentropy


model4.compile(optimizer=tf.keras.optimizers.RMSprop(momentum=0.2), loss="binary_crossentropy", metrics=["accuracy"])

In [ ]:
class MyCLRuleMonitor(tf.keras.callbacks.Callback):
  def __init__(self,cl):
    super(MyCLRuleMonitor,self).__init__()
    self.cl=cl

  def on_epoch_end(self,epoch,logs=None):
    testScore = logs['val_accuracy']
    trainScore = logs['accuracy']

    if testScore > trainScore and testScore >= self.cl:
      self.model.stop_training=True

In [ ]:
model4.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=10000, callbacks=[MyCLRuleMonitor(0.9)])

Epoch 1/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 3s 91ms/step - accuracy: 0.5395 - loss: 0.8882 - val_accuracy: 0.6500 - val_loss: 0.8713
Epoch 2/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6773 - loss: 0.8586 - val_accuracy: 0.6500 - val_loss: 0.8563
Epoch 3/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6625 - loss: 0.8380 - val_accuracy: 0.6500 - val_loss: 0.8419
Epoch 4/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6254 - loss: 0.8403 - val_accuracy: 0.6500 - val_loss: 0.8271
Epoch 5/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6380 - loss: 0.8256 - val_accuracy: 0.6500 - val_loss: 0.8124
Epoch 6/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6570 - loss: 0.8018 - val_accuracy: 0.6500 - val_loss: 0.7982
Epoch 7/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6506 - loss: 0.7876 - val_accuracy: 0.6500 - val_loss: 0.7836
Epoch 8/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6534 - loss: 0.7765 - val_accuracy: 0.6500 - val_loss: 0.7691
Epoch 9/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6442 - loss: 0.7620 - val_accuracy: 0.6500 - val_loss: 0.7546
Epoch 10/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6646 - loss: 0.7299 - val_accuracy: 0.6500 - val_loss: 0.7408
Epoch 11/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6431 - loss: 0.7308 - val_accuracy: 0.6500 - val_loss: 0.7272
Epoch 12/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6189 - loss: 0.7357 - val_accuracy: 0.6500 - val_loss: 0.7139
Epoch 13/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6341 - loss: 0.7039 - val_accuracy: 0.6500 - val_loss: 0.7015
Epoch 14/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6090 - loss: 0.7168 - val_accuracy: 0.6500 - val_loss: 0.6892
Epoch 15/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6900 - loss: 0.6751 - val_accuracy: 0.6500 - val_loss: 0.6779
Epoch 16/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6602 - loss: 0.6682 - val_accuracy: 0.6500 - val_loss: 0.6667
Epoch 17/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6632 - loss: 0.6467 - val_accuracy: 0.6500 - val_loss: 0.6560
Epoch 18/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6019 - loss: 0.6772 - val_accuracy: 0.6500 - val_loss: 0.6448
Epoch 19/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6431 - loss: 0.6392 - val_accuracy: 0.6500 - val_loss: 0.6342
Epoch 20/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6701 - loss: 0.6219 - val_accuracy: 0.6500 - val_loss: 0.6244
Epoch 21/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6618 - loss: 0.6143 - val_accuracy: 0.6500 - val_loss: 0.6148
Epoch 22/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6686 - loss: 0.5930 - val_accuracy: 0.6500 - val_loss: 0.6052
Epoch 23/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6356 - loss: 0.6000 - val_accuracy: 0.6500 - val_loss: 0.5954
Epoch 24/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6397 - loss: 0.6119 - val_accuracy: 0.6500 - val_loss: 0.5858
Epoch 25/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6295 - loss: 0.5884 - val_accuracy: 0.6500 - val_loss: 0.5768
Epoch 26/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6080 - loss: 0.5967 - val_accuracy: 0.6500 - val_loss: 0.5679
Epoch 27/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6539 - loss: 0.5699 - val_accuracy: 0.7500 - val_loss: 0.5593
Epoch 28/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7629 - loss: 0.5758 - val_accuracy: 0.8125 - val_loss: 0.5503
Epoch 29/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7637 - loss: 0.5723 - val_accuracy: 0.8125 - val_loss: 0.5418
Epoch 30/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7871 - loss: 0.5641 - val_accuracy: 0.8250 - val_loss: 0.5335
Epoch 31/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7898 - loss: 0.5454 - val_accuracy: 0.8375 - val_loss: 0.5258
Epoch 32/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7773 - loss: 0.5400 - val_accuracy: 0.8125 - val_loss: 0.5182
Epoch 33/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8156 - loss: 0.5145 - val_accuracy: 0.8125 - val_loss: 0.5113
Epoch 34/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8106 - loss: 0.5229 - val_accuracy: 0.8125 - val_loss: 0.5044
Epoch 35/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7861 - loss: 0.5068 - val_accuracy: 0.8125 - val_loss: 0.4976
Epoch 36/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7934 - loss: 0.5244 - val_accuracy: 0.8125 - val_loss: 0.4910
Epoch 37/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8011 - loss: 0.5335 - val_accuracy: 0.8125 - val_loss: 0.4851
Epoch 38/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8073 - loss: 0.5079 - val_accuracy: 0.8250 - val_loss: 0.4793
Epoch 39/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8002 - loss: 0.5268 - val_accuracy: 0.8250 - val_loss: 0.4734
Epoch 40/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7882 - loss: 0.5047 - val_accuracy: 0.8250 - val_loss: 0.4682
Epoch 41/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8338 - loss: 0.4708 - val_accuracy: 0.8375 - val_loss: 0.4635
Epoch 42/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8315 - loss: 0.4723 - val_accuracy: 0.8500 - val_loss: 0.4584
Epoch 43/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8051 - loss: 0.4792 - val_accuracy: 0.8500 - val_loss: 0.4539
Epoch 44/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8206 - loss: 0.4609 - val_accuracy: 0.8625 - val_loss: 0.4497
Epoch 45/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8482 - loss: 0.4691 - val_accuracy: 0.8625 - val_loss: 0.4460
Epoch 46/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8119 - loss: 0.4972 - val_accuracy: 0.8625 - val_loss: 0.4420
Epoch 47/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8506 - loss: 0.4540 - val_accuracy: 0.8750 - val_loss: 0.4381
Epoch 48/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8391 - loss: 0.4667 - val_accuracy: 0.8750 - val_loss: 0.4348
Epoch 49/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8594 - loss: 0.4324 - val_accuracy: 0.9125 - val_loss: 0.4316

# L2 Regularization

In [ ]:
#Architect the model
import tensorflow as tf

model5 = tf.keras.Sequential()

model5.add(tf.keras.layers.Dense(units = 6 , kernel_regularizer='l2', activation="relu", input_shape=(2,)))
model5.add(tf.keras.layers.Dense(units = 6 , kernel_regularizer='l2' , activation="relu"))
model5.add(tf.keras.layers.Dense(units = 1 , activation="sigmoid"))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
#Compile Model

#For Classification
# Loss Function:
# a. Binary Classification: binary_crossentropy
# b. Multi-class Classification: categorical_crossentropy | sparse_categorical_crossentropy


model5.compile(optimizer=tf.keras.optimizers.RMSprop(momentum=0.2), loss="binary_crossentropy", metrics=["accuracy"])

In [ ]:
class MyCLRuleMonitor(tf.keras.callbacks.Callback):
  def __init__(self,cl):
    super(MyCLRuleMonitor,self).__init__()
    self.cl=cl

  def on_epoch_end(self,epoch,logs=None):
    testScore = logs['val_accuracy']
    trainScore = logs['accuracy']

    if testScore > trainScore and testScore >= self.cl:
      self.model.stop_training=True

In [ ]:
model5.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=10000, callbacks=[MyCLRuleMonitor(0.9)])

Epoch 1/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.7674 - loss: 0.7510 - val_accuracy: 0.8375 - val_loss: 0.7352
Epoch 2/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7730 - loss: 0.7292 - val_accuracy: 0.8000 - val_loss: 0.7144
Epoch 3/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7519 - loss: 0.7207 - val_accuracy: 0.8375 - val_loss: 0.6959
Epoch 4/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8110 - loss: 0.6879 - val_accuracy: 0.8500 - val_loss: 0.6779
Epoch 5/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7930 - loss: 0.6769 - val_accuracy: 0.8500 - val_loss: 0.6601
Epoch 6/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8099 - loss: 0.6536 - val_accuracy: 0.8500 - val_loss: 0.6424
Epoch 7/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8114 - loss: 0.6425 - val_accuracy: 0.8500 - val_loss: 0.6249
Epoch 8/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7929 - loss: 0.6380 - val_accuracy: 0.8500 - val_loss: 0.6070
Epoch 9/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7770 - loss: 0.6286 - val_accuracy: 0.8500 - val_loss: 0.5890
Epoch 10/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8112 - loss: 0.5980 - val_accuracy: 0.8750 - val_loss: 0.5716
Epoch 11/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8113 - loss: 0.5791 - val_accuracy: 0.8750 - val_loss: 0.5551
Epoch 12/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8591 - loss: 0.5516 - val_accuracy: 0.8750 - val_loss: 0.5393
Epoch 13/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8265 - loss: 0.5608 - val_accuracy: 0.8750 - val_loss: 0.5238
Epoch 14/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8205 - loss: 0.5399 - val_accuracy: 0.8750 - val_loss: 0.5088
Epoch 15/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8280 - loss: 0.5204 - val_accuracy: 0.8750 - val_loss: 0.4947
Epoch 16/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8197 - loss: 0.5295 - val_accuracy: 0.8750 - val_loss: 0.4811
Epoch 17/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8546 - loss: 0.4857 - val_accuracy: 0.8750 - val_loss: 0.4680
Epoch 18/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8489 - loss: 0.4728 - val_accuracy: 0.8875 - val_loss: 0.4559
Epoch 19/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8386 - loss: 0.4823 - val_accuracy: 0.8875 - val_loss: 0.4439
Epoch 20/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8606 - loss: 0.4624 - val_accuracy: 0.9000 - val_loss: 0.4335
Epoch 21/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8087 - loss: 0.4948 - val_accuracy: 0.9000 - val_loss: 0.4232
Epoch 22/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8672 - loss: 0.4435 - val_accuracy: 0.9000 - val_loss: 0.4142
Epoch 23/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8503 - loss: 0.4621 - val_accuracy: 0.9000 - val_loss: 0.4062
Epoch 24/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8605 - loss: 0.4361 - val_accuracy: 0.9000 - val_loss: 0.3984
Epoch 25/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8605 - loss: 0.4353 - val_accuracy: 0.9000 - val_loss: 0.3911
Epoch 26/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8623 - loss: 0.4322 - val_accuracy: 0.9000 - val_loss: 0.3845
Epoch 27/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8723 - loss: 0.4177 - val_accuracy: 0.9000 - val_loss: 0.3783
Epoch 28/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8582 - loss: 0.4306 - val_accuracy: 0.9000 - val_loss: 0.3725
Epoch 29/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8798 - loss: 0.4046 - val_accuracy: 0.9125 - val_loss: 0.3671

In [ ]:
#Try these rules to create a model for
# 2. Wine Quality Dataset --- CL= 0.8

#Ensure you stratify the splits.